apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicdspacex
  name: cicdlocation-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: location-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: location-app
    spec:
      containers:
      - image: deveendocker/location-user:main
        imagePullPolicy: Always
        name: location-app
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  namespace: cicdspacex
  name: cicdlocation-service
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: location-app
  type: LoadBalancer
status:
  loadBalancer: {}
